name: China Calendars
on:
  push:
  schedule:
    - cron: "0 2 * * ?"

jobs:
  holiday:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Download google calendar
        run: curl https://calendar.google.com/calendar/ical/zh.china%23holiday%40group.v.calendar.google.com/public/basic.ics -o china/holiday.ics
      
      - name: Trim holiday.ics
        run: |
          sed '/^DTSTAMP/ d' china/holiday.ics > china/holiday.ics.tmp
          mv china/holiday.ics.tmp china/holiday.ics
      # Runs a set of commands using the runners shell
      - name: Commit and push if changed
        run: |
          git config --global user.email "mr.imuz@gmail.com"
          git config --global user.name "calendar-robot"
          git diff
          git add .
          git commit -m "Github Action Auto Updated China Holiday Calendar"
          git push
