name: Gitee
on:
  push:
jobs:
  holiday:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Push Commit To Gitee
        run: |
          git fetch origin
          git remote add mirror https://aimuz:${{ secrets.GITEE_TOKEN }}@gitee.com/aimuz/simple-calendars
          git push --tags --force --prune mirror "refs/remotes/origin/*:refs/heads/*"
